import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { GeneratorError, describe } from './errors.js';
import type { ShardSet } from './shards.js';

const CLIENT_DATA_FILE = resolve(
    import.meta.dirname,
    '..',
    '..',
    '..',
    'packages',
    'geo',
    'src',
    'countries.data.ts',
);

/**
 * The country index is the one layer that ships in the consumer's bundle rather than over the
 * network: 250 rows, 6.3 KB raw and 1.9 KB brotli, against a round trip on the critical path of
 * every registration and checkout form. Everything below it — regions, cities — stays fetched,
 * because that is where the megabytes are.
 *
 * Generated, never hand-edited, and written as TypeScript rather than JSON so consumers get the
 * literal types and bundlers can drop what a given app does not touch.
 */
export async function writeBundledCountries(shardSet: ShardSet): Promise<number> {
    const rows = shardSet.countries
        .map(([code, name]) => `  ${JSON.stringify(code)}: ${JSON.stringify(name)}`)
        .join(',\n');

    const source = [
        '// Generated by tools/generator. Do not edit.',
        `// Source: dr5hn countries-states-cities-database, ${shardSet.countries.length} countries.`,
        '',
        'export const COUNTRY_NAMES: Record<string, string> = {',
        rows,
        '}',
        '',
    ].join('\n');

    try {
        await writeFile(CLIENT_DATA_FILE, source, 'utf8');
    } catch (cause) {
        throw new GeneratorError(`could not write ${CLIENT_DATA_FILE}: ${describe(cause)}`);
    }

    return Buffer.byteLength(source, 'utf8');
}
